import type { ContextMessage } from './types';

// Context-aware dynamic messages with mode tags for behavior-aware selection
export const contextMessages: Record<string, ContextMessage[]> = {
  hero: [
    { en: 'Chat with ORBIT!', bn: 'ORBIT-এর সাথে চ্যাট করুন!' },
    { en: 'Ready to launch your project?', bn: 'প্রজেক্ট শুরু করতে প্রস্তুত?' },
    { en: 'Need a custom AI solution?', bn: 'কাস্টম এআই সলিউশন লাগবে?' },
    { en: "Let's transform your ideas into reality!", bn: 'আপনার আইডিয়াগুলোকে বাস্তবে রূপ দিই চলুন!' },
    { en: 'Looking for a reliable tech partner?', bn: 'নির্ভরযোগ্য টেক পার্টনার খুঁজছেন?' },
    { en: 'Hey! Got a project in mind? 🚀', bn: 'হেই! কোনো প্রজেক্ট মাথায় আছে? 🚀' },
    { en: 'Your next big idea starts here ✨', bn: 'আপনার পরবর্তী বড় আইডিয়া এখান থেকেই শুরু ✨' },
    { en: 'I can help you get started fast!', bn: 'আমি আপনাকে দ্রুত শুরু করতে সাহায্য করতে পারি!' },
    { en: 'Thinking about going digital?', bn: 'ডিজিটাল হওয়ার কথা ভাবছেন?' },
    { en: '3 clients launched this week! You next?', bn: 'এই সপ্তাহে ৩টি ক্লায়েন্ট লঞ্চ! আপনি পরবর্তী?' },
    { en: 'I know the perfect solution for you 😊', bn: 'আমি আপনার জন্য পারফেক্ট সলিউশন জানি 😊' },
  ],
  services: [
    { en: 'Need help choosing a service?', bn: 'সঠিক সেবা খুঁজতে সাহায্য লাগবে?' },
    { en: 'Want to know more about our services?', bn: 'আমাদের সার্ভিস নিয়ে আরও জানতে চান?' },
    { en: 'We build Web, AI, and Mobile Apps.', bn: 'আমরা ওয়েব, এআই এবং মোবাইল অ্যাপ বানাই।' },
    { en: 'Looking for End-to-End Development?', bn: 'এন্ড-টু-এন্ড ডেভেলপমেন্ট খুঁজছেন?' },
    { en: 'Ask me about our tech expertise!', bn: 'আমাদের টেক এক্সপার্টিজ সম্পর্কে জিজ্ঞেস করুন!' },
    { en: 'Which service caught your eye? 👀', bn: 'কোন সেবাটি আপনার চোখে পড়েছে? 👀' },
    { en: 'AI chatbots are trending! Want one?', bn: 'AI চ্যাটবট এখন ট্রেন্ডিং! একটা চান?' },
    { en: 'We handle everything from A to Z 💪', bn: 'আমরা A থেকে Z সব হ্যান্ডেল করি 💪' },
    { en: 'Confused which service fits you best?', bn: 'কোন সেবাটি আপনার জন্য সেরা?' },
    { en: 'Custom software, tailored for you 🎯', bn: 'আপনার জন্য কাস্টম সফটওয়্যার 🎯' },
  ],
  project: [
    { en: "Like our previous work?", bn: 'আমাদের কাজগুলো ভালো লেগেছে?' },
    { en: "Let's build something like this for you.", bn: 'আপনার জন্যও এমন কিছু বানাতে পারি।' },
    { en: 'Want a completely custom solution?', bn: 'আপনার জন্য সম্পূর্ণ কাস্টম সলিউশন চাই?' },
    { en: 'Check out the details of these projects.', bn: 'এই প্রজেক্টগুলোর বিস্তারিত দেখতে পারেন।' },
    { en: 'Tell me your project requirements!', bn: 'আপনার প্রজেক্টের রিকোয়ারমেন্টগুলো জানান!' },
    { en: 'This could be YOUR project next! 🔥', bn: 'এটা আপনার পরবর্তী প্রজেক্ট! 🔥' },
    { en: 'Impressed? Let me show you more!', bn: 'মুগ্ধ হয়েছেন? আরও দেখাতে পারি!' },
    { en: 'We built this in just 2 weeks! ⚡', bn: 'আমরা এটা মাত্র ২ সপ্তাহে বানিয়েছি! ⚡' },
    { en: 'Imagine your brand here!', bn: 'এখানে আপনার ব্র্যান্ড কল্পনা করুন!' },
    { en: 'Real projects. Real results. Ask me!', bn: 'আসল প্রজেক্ট। আসল ফলাফল। জিজ্ঞেস করুন!' },
  ],
  'tech-stack': [
    { en: 'Curious about our technologies?', bn: 'আমাদের প্রযুক্তি সম্পর্কে জানতে চান?' },
    { en: 'Need a specific tech stack?', bn: 'কোনো নির্দিষ্ট প্রযুক্তির কাজ খুঁজছেন?' },
    { en: 'We use modern, scalable tech.', bn: 'আমরা আধুনিক এবং স্কেলেবল প্রযুক্তি ব্যবহার করি।' },
    { en: 'Ask me about any specific tool.', bn: 'কোনো নির্দিষ্ট টুল সম্পর্কে জিজ্ঞেস করতে পারেন।' },
    { en: 'React, Next.js, AI - we do it all!', bn: 'React, Next.js, AI - সব করি!' },
    { en: 'Tech choices matter. Let me guide you!', bn: 'প্রযুক্তি নির্বাচন গুরুত্বপূর্ণ। আমি গাইড করি!' },
    { en: 'We pick the right stack for YOUR needs', bn: 'আপনার প্রয়োজন অনুযায়ী সেরা স্ট্যাক বাছাই করি' },
    { en: 'Wondering which tech is best for you?', bn: 'কোন প্রযুক্তি আপনার জন্য সেরা ভাবছেন?' },
  ],
  'why-us': [
    { en: 'Want to know why clients choose us?', bn: 'ক্লায়েন্টরা কেন আমাদের ভালোবাসে?' },
    { en: 'We guarantee 100% satisfaction.', bn: 'আমরা ১০০% গ্যারান্টি দিয়ে কাজ করি।' },
    { en: 'Ask about our communication process.', bn: 'আমাদের কমিউনিকেশন প্রসেস সম্পর্কে জানুন।' },
    { en: 'We deliver on time, every time.', bn: 'আমরা সবসময় ঠিক সময়ে কাজ ডেলিভারি দিই।' },
    { en: 'Still deciding? Let me convince you!', bn: 'এখনও ভাবছেন? আমি কনভিন্স করি!' },
    { en: 'Our clients keep coming back!', bn: 'আমাদের ক্লায়েন্টরা বারবার ফিরে আসে!' },
    { en: 'Direct communication - no middlemen!', bn: 'সরাসরি যোগাযোগ - কোনো মধ্যস্থতাকারী নেই!' },
    { en: 'Milestone-based payments. Zero risk!', bn: 'মাইলস্টোন-ভিত্তিক পেমেন্ট। শূন্য ঝুঁকি!' },
  ],
  leadership: [
    { en: 'Want to talk to our leadership team?', bn: 'আমাদের লিডারশিপ টিমের সাথে কথা বলবেন?' },
    { en: 'Any questions for our founders?', bn: 'আমাদের ফাউন্ডারদের জন্য কোনো প্রশ্ন আছে?' },
  ],
  contact: [
    { en: 'Have a specific question?', bn: 'কোনো নির্দিষ্ট প্রশ্ন আছে?' },
    { en: 'Drop me a message here!', bn: 'এখানে আমাকে ম্যাসেজ দিন!' },
    { en: 'Want to book a free consultation?', bn: 'ফ্রি কনসাল্টেশন বুক করতে চান?' },
    { en: 'I can connect you to our team.', bn: 'আমি আপনাকে আমাদের টিমের সাথে কানেক্ট করতে পারি।' },
    { en: 'Ready to start? Let me help!', bn: 'শুরু করতে প্রস্তুত? আমি সাহায্য করি!' },
    { en: 'One message away from your dream app!', bn: 'আপনার স্বপ্নের অ্যাপ থেকে মাত্র এক মেসেজ দূরে!' },
    { en: 'I respond faster than email!', bn: 'আমি ইমেইলের চেয়ে দ্রুত উত্তর দিই!' },
    { en: 'No commitment - just a friendly chat', bn: 'কোনো বাধ্যবাধকতা নেই - শুধু বন্ধুত্বপূর্ণ আলাপ' },
  ],
  default: [
    { en: 'Chat with ORBIT', bn: 'ORBIT-এর সাথে চ্যাট করুন' },
    { en: 'How can I help you today?', bn: 'কীভাবে সাহায্য করতে পারি?' },
    { en: 'Still here if you need me!', bn: 'আমি এখানেই আছি, কোনো সাহায্য লাগলে বলবেন!' },
    { en: 'Have any questions?', bn: 'আপনার কোনো প্রশ্ন আছে?' },
    { en: "Let's discuss your project.", bn: 'চলুন আপনার প্রজেক্ট নিয়ে আলোচনা করি।' },
    { en: 'Need a quick estimate?', bn: 'দ্রুত প্রজেক্টের খরচ জানতে চান?' },
    { en: 'I noticed you are browsing around!', bn: 'দেখলাম আপনি ঘুরে দেখছেন!' },
    { en: 'Got 30 seconds? Let me surprise you!', bn: '৩০ সেকেন্ড আছে? আমি চমকে দিই!' },
    { en: 'Fun fact: I never sleep!', bn: 'মজার তথ্য: আমি কখনো ঘুমাই না!' },
    { en: 'Your competitors are already building!', bn: 'আপনার প্রতিযোগীরা ইতিমধ্যে তৈরি করছে!' },
    { en: 'Tap me for instant answers!', bn: 'তাৎক্ষণিক উত্তরের জন্য আমাকে ট্যাপ করুন!' },
    { en: 'I can help you save time and money!', bn: 'আমি আপনার সময় ও টাকা বাঁচাতে পারি!' },
  ],
  reviews: [
    { en: 'See what our clients say about us!', bn: 'আমাদের ক্লায়েন্টরা কী বলে দেখুন!', mode: 'casual' },
    { en: 'Real reviews from real clients.', bn: 'আসল ক্লায়েন্টদের আসল রিভিউ।', mode: 'casual' },
    { en: 'These reviews speak for themselves!', bn: 'এই রিভিউগুলো নিজেই কথা বলে!', mode: 'casual' },
    { en: 'Hundreds of happy clients worldwide', bn: 'বিশ্বজুড়ে শত শত খুশি ক্লায়েন্ট', mode: 'engaging' },
    { en: 'Your success story could be next!', bn: 'আপনার সাফল্যের গল্প পরবর্তী হতে পারে!', mode: 'engaging' },
    { en: 'Join 100+ satisfied businesses!', bn: '১০০+ সন্তুষ্ট ব্যবসায়ে যোগ দিন!', mode: 'action' },
    { en: '5-star rated by every client! Ask me why', bn: 'প্রতিটি ক্লায়েন্ট ৫-স্টার দিয়েছে! জিজ্ঞেস করুন কেন', mode: 'action' },
  ],
  returning: [
    { en: 'Welcome back! Missed you!', bn: 'ফিরে এসেছেন! আপনাকে মিস করেছি!', mode: 'returning' },
    { en: 'Hey, you are back! Need anything?', bn: 'হেই, ফিরে এসেছেন! কিছু লাগবে?', mode: 'returning' },
    { en: 'Good to see you again!', bn: 'আবার দেখে ভালো লাগলো!', mode: 'returning' },
    { en: 'Still thinking? Let me help decide!', bn: 'এখনো ভাবছেন? সিদ্ধান্ত নিতে সাহায্য করি!', mode: 'returning' },
    { en: 'Back for more? I am here for you!', bn: 'আরো জানতে ফিরে এসেছেন? আমি এখানেই আছি!', mode: 'returning' },
    { en: 'Picked up where you left off?', bn: 'যেখানে ছেড়েছিলেন সেখান থেকে শুরু করবেন?', mode: 'returning' },
  ]
};
